package com.mycompany.x0;

public class Juego extends javax.swing.JFrame {

    private String nombreX;
    private String nombre0;

    String jugador = "X";

    int f1c1 = 0;
    int f1c2 = 0;
    int f1c3 = 0;
    int f2c1 = 0;
    int f2c2 = 0;
    int f2c3 = 0;
    int f3c1 = 0;
    int f3c2 = 0;
    int f3c3 = 0;

    int ganarFila1X = 3;
    int ganarFila2X = 3;
    int ganarFila3X = 3;

    int ganarFila10 = 3;
    int ganarFila20 = 3;
    int ganarFila30 = 3;

    int ganarColumna1X = 3;
    int ganarColumna2X = 3;
    int ganarColumna3X = 3;

    int ganarColumna10 = 3;
    int ganarColumna20 = 3;
    int ganarColumna30 = 3;

    int ganarDiagonal1X = 3;
    int ganarDiagonal2X = 3;
    int ganarDiagonal10 = 3;
    int ganarDiagonal20 = 3;

    int fin = 0;
    String resultado = " ";

    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();

        btnLimpiar.setVisible(false);
        btnSalir.setVisible(false);
        Resultado.setVisible(false);

        this.setLocationRelativeTo(null);
        setNombres();
    }

    public void setNombres() {
        nombreX = Inicio_Registro.getNombreX();
        nombre0 = Inicio_Registro.getNombre0();

        labelNombreX.setText(nombreX);
        labelNombre0.setText(nombre0);

        turno.setText("Turno de " + nombreX);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel = new javax.swing.JPanel();
        X0 = new javax.swing.JLabel();
        jLabelX = new javax.swing.JLabel();
        labelNombreX = new javax.swing.JLabel();
        jLabel0 = new javax.swing.JLabel();
        labelNombre0 = new javax.swing.JLabel();
        turno = new javax.swing.JLabel();
        Ingrese = new javax.swing.JLabel();
        jLabelFila = new javax.swing.JLabel();
        jLabelColumna = new javax.swing.JLabel();
        CoordenadaColumna = new javax.swing.JTextField();
        CoordenadaFila = new javax.swing.JTextField();
        jButtonAceptar = new javax.swing.JButton();
        jPanelRablero = new javax.swing.JPanel();
        jPanelF1C1 = new javax.swing.JPanel();
        jLabelF1C1 = new javax.swing.JLabel();
        jPanelF1C2 = new javax.swing.JPanel();
        jLabelF1C2 = new javax.swing.JLabel();
        jPanelF1C3 = new javax.swing.JPanel();
        jLabelF1C3 = new javax.swing.JLabel();
        jPanelF2C1 = new javax.swing.JPanel();
        jLabelF2C1 = new javax.swing.JLabel();
        jPanelF2C2 = new javax.swing.JPanel();
        jLabelF2C2 = new javax.swing.JLabel();
        jPanelF2C3 = new javax.swing.JPanel();
        jLabelF2C3 = new javax.swing.JLabel();
        jPanelF3C1 = new javax.swing.JPanel();
        jLabelF3C1 = new javax.swing.JLabel();
        jPanelF3C2 = new javax.swing.JPanel();
        jLabelF3C2 = new javax.swing.JLabel();
        jPanelF3C3 = new javax.swing.JPanel();
        jLabelF3C3 = new javax.swing.JLabel();
        Resultado = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel6.setText("Nombre 0");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        X0.setFont(new java.awt.Font("Helvetica Neue", 1, 60)); // NOI18N
        X0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        X0.setText("X 0");
        jPanel.add(X0, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 22, -1, -1));

        jLabelX.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabelX.setText("X: ");
        jPanel.add(jLabelX, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 165, -1, -1));

        labelNombreX.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        labelNombreX.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelNombreX.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                labelNombreXComponentAdded(evt);
            }
        });
        jPanel.add(labelNombreX, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 165, 120, 29));

        jLabel0.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel0.setText("0: ");
        jPanel.add(jLabel0, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 212, -1, -1));

        labelNombre0.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        labelNombre0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel.add(labelNombre0, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 212, 120, 29));

        turno.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jPanel.add(turno, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 284, 214, 43));

        Ingrese.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Ingrese.setText("Ingrese las coordenadas del movimiento:");
        jPanel.add(Ingrese, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 344, -1, -1));

        jLabelFila.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFila.setText("Fila");
        jPanel.add(jLabelFila, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 389, -1, -1));

        jLabelColumna.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelColumna.setText("Columna");
        jPanel.add(jLabelColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 389, -1, -1));
        jPanel.add(CoordenadaColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 333, 76, 50));
        jPanel.add(CoordenadaFila, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 333, 78, 50));

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAceptarMouseClicked(evt);
            }
        });
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        jPanel.add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 343, -1, 30));

        jPanelRablero.setBackground(new java.awt.Color(0, 0, 0));

        jLabelF1C1.setBackground(new java.awt.Color(255, 0, 102));
        jLabelF1C1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabelF1C1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelF1C1.setText(" ");

        javax.swing.GroupLayout jPanelF1C1Layout = new javax.swing.GroupLayout(jPanelF1C1);
        jPanelF1C1.setLayout(jPanelF1C1Layout);
        jPanelF1C1Layout.setHorizontalGroup(
            jPanelF1C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF1C1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanelF1C1Layout.setVerticalGroup(
            jPanelF1C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF1C1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jLabelF1C2.setBackground(new java.awt.Color(255, 0, 102));
        jLabelF1C2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabelF1C2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelF1C2Layout = new javax.swing.GroupLayout(jPanelF1C2);
        jPanelF1C2.setLayout(jPanelF1C2Layout);
        jPanelF1C2Layout.setHorizontalGroup(
            jPanelF1C2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF1C2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanelF1C2Layout.setVerticalGroup(
            jPanelF1C2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF1C2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabelF1C3.setBackground(new java.awt.Color(255, 0, 102));
        jLabelF1C3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabelF1C3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelF1C3Layout = new javax.swing.GroupLayout(jPanelF1C3);
        jPanelF1C3.setLayout(jPanelF1C3Layout);
        jPanelF1C3Layout.setHorizontalGroup(
            jPanelF1C3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF1C3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelF1C3Layout.setVerticalGroup(
            jPanelF1C3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF1C3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabelF2C1.setBackground(new java.awt.Color(255, 0, 102));
        jLabelF2C1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabelF2C1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelF2C1Layout = new javax.swing.GroupLayout(jPanelF2C1);
        jPanelF2C1.setLayout(jPanelF2C1Layout);
        jPanelF2C1Layout.setHorizontalGroup(
            jPanelF2C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF2C1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanelF2C1Layout.setVerticalGroup(
            jPanelF2C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF2C1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jLabelF2C2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabelF2C2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelF2C2Layout = new javax.swing.GroupLayout(jPanelF2C2);
        jPanelF2C2.setLayout(jPanelF2C2Layout);
        jPanelF2C2Layout.setHorizontalGroup(
            jPanelF2C2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF2C2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanelF2C2Layout.setVerticalGroup(
            jPanelF2C2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF2C2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jLabelF2C3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabelF2C3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelF2C3Layout = new javax.swing.GroupLayout(jPanelF2C3);
        jPanelF2C3.setLayout(jPanelF2C3Layout);
        jPanelF2C3Layout.setHorizontalGroup(
            jPanelF2C3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF2C3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanelF2C3Layout.setVerticalGroup(
            jPanelF2C3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF2C3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jLabelF3C1.setBackground(new java.awt.Color(255, 0, 102));
        jLabelF3C1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabelF3C1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelF3C1Layout = new javax.swing.GroupLayout(jPanelF3C1);
        jPanelF3C1.setLayout(jPanelF3C1Layout);
        jPanelF3C1Layout.setHorizontalGroup(
            jPanelF3C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF3C1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanelF3C1Layout.setVerticalGroup(
            jPanelF3C1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF3C1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jLabelF3C2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabelF3C2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelF3C2Layout = new javax.swing.GroupLayout(jPanelF3C2);
        jPanelF3C2.setLayout(jPanelF3C2Layout);
        jPanelF3C2Layout.setHorizontalGroup(
            jPanelF3C2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF3C2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanelF3C2Layout.setVerticalGroup(
            jPanelF3C2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF3C2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jLabelF3C3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabelF3C3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelF3C3Layout = new javax.swing.GroupLayout(jPanelF3C3);
        jPanelF3C3.setLayout(jPanelF3C3Layout);
        jPanelF3C3Layout.setHorizontalGroup(
            jPanelF3C3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF3C3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanelF3C3Layout.setVerticalGroup(
            jPanelF3C3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelF3C3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelRableroLayout = new javax.swing.GroupLayout(jPanelRablero);
        jPanelRablero.setLayout(jPanelRableroLayout);
        jPanelRableroLayout.setHorizontalGroup(
            jPanelRableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRableroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelRableroLayout.createSequentialGroup()
                        .addComponent(jPanelF1C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelF1C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelF1C3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelRableroLayout.createSequentialGroup()
                        .addComponent(jPanelF2C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelF2C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelF2C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRableroLayout.createSequentialGroup()
                        .addComponent(jPanelF3C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelF3C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelF3C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRableroLayout.setVerticalGroup(
            jPanelRableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRableroLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelRableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelRableroLayout.createSequentialGroup()
                        .addGroup(jPanelRableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelF1C3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelF1C1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelF1C2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelF2C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelF2C3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanelF2C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelF3C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelF3C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelF3C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel.add(jPanelRablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        Resultado.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        Resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Resultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel.add(Resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 154, 153));

        btnLimpiar.setText("Reiniciar");
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
        });
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 660, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        jPanel.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 700, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAceptarMouseClicked

        int fila = Integer.parseInt(CoordenadaFila.getText());
        int columna = Integer.parseInt(CoordenadaColumna.getText());

        int cambio = 0;

        //Movimientos X
        if (fila == 1 && columna == 1 && f1c1 == 0 && jugador.equals("X")) {
            jLabelF1C1.setText(jugador);
            f1c1 = 1;
            ganarFila1X--;
            ganarColumna1X--;
            ganarDiagonal1X--;
            cambio = 1;

        } else if (fila == 1 && columna == 2 && f1c2 == 0 && jugador.equals("X")) {
            jLabelF1C2.setText(jugador);
            f1c2 = 1;
            ganarFila1X--;
            ganarColumna2X--;
            cambio = 1;

        } else if (fila == 1 && columna == 3 && f1c3 == 0 && jugador.equals("X")) {
            jLabelF1C3.setText(jugador);
            f1c3 = 1;
            ganarFila1X--;
            ganarColumna3X--;
            ganarDiagonal2X--;
            ganarDiagonal20--;
            cambio = 1;

        } else if (fila == 2 && columna == 1 && f2c1 == 0 && jugador.equals("X")) {
            jLabelF2C1.setText(jugador);
            f2c1 = 1;
            ganarFila2X--;
            ganarColumna1X--;
            cambio = 1;

        } else if (fila == 2 && columna == 2 && f2c2 == 0 && jugador.equals("X")) {
            jLabelF2C2.setText(jugador);
            f2c2 = 1;
            ganarFila2X--;
            ganarColumna2X--;
            ganarDiagonal1X--;
            ganarDiagonal2X--;
            ganarDiagonal10 = 4;
            ganarDiagonal20 = 4;
            cambio = 1;

        } else if (fila == 2 && columna == 3 && f2c3 == 0 && jugador.equals("X")) {
            jLabelF2C3.setText(jugador);
            f2c3 = 1;
            ganarFila2X--;
            ganarColumna3X--;
            cambio = 1;

        } else if (fila == 3 && columna == 1 && f3c1 == 0 && jugador.equals("X")) {
            jLabelF3C1.setText(jugador);
            f3c1 = 1;
            ganarFila3X--;
            ganarColumna1X--;
            ganarDiagonal2X--;
            cambio = 1;

        } else if (fila == 3 && columna == 2 && f3c2 == 0 && jugador.equals("X")) {
            jLabelF3C2.setText(jugador);
            f3c2 = 1;
            ganarFila3X--;
            ganarColumna2X--;
            cambio = 1;

        } else if (fila == 3 && columna == 3 && f3c3 == 0 && jugador.equals("X")) {
            jLabelF3C3.setText(jugador);
            f3c3 = 1;
            ganarFila3X--;
            ganarColumna3X--;
            ganarDiagonal1X--;
            cambio = 1;

            //Movimientos 0
        } else if (fila == 1 && columna == 1 && f1c1 == 0 && jugador.equals("O")) {
            jLabelF1C1.setText(jugador);
            f1c1 = 1;
            ganarFila10--;
            ganarColumna10--;
            ganarDiagonal10--;
            cambio = 1;

        } else if (fila == 1 && columna == 2 && f1c2 == 0 && jugador.equals("O")) {
            jLabelF1C2.setText(jugador);
            f1c2 = 1;
            ganarFila10--;
            ganarColumna20--;
            cambio = 1;

        } else if (fila == 1 && columna == 3 && f1c3 == 0 && jugador.equals("O")) {
            jLabelF1C3.setText(jugador);
            f1c3 = 1;
            ganarFila10--;
            ganarColumna30--;
            ganarDiagonal20--;
            cambio = 1;

        } else if (fila == 2 && columna == 1 && f2c1 == 0 && jugador.equals("O")) {
            jLabelF2C1.setText(jugador);
            f2c1 = 1;
            ganarFila20--;
            ganarColumna10--;
            cambio = 1;

        } else if (fila == 2 && columna == 2 && f2c2 == 0 && jugador.equals("O")) {
            jLabelF2C2.setText(jugador);
            f2c2 = 1;
            ganarFila20--;
            ganarColumna20--;
            ganarDiagonal10--;
            ganarDiagonal20--;
            ganarDiagonal1X = 4;
            ganarDiagonal2X = 4;
            cambio = 1;

        } else if (fila == 2 && columna == 3 && f2c3 == 0 && jugador.equals("O")) {
            jLabelF2C3.setText(jugador);
            f2c3 = 1;
            ganarFila20--;
            ganarColumna30--;
            cambio = 1;

        } else if (fila == 3 && columna == 1 && f3c1 == 0 && jugador.equals("O")) {
            jLabelF3C1.setText(jugador);
            f3c1 = 1;
            ganarFila30--;
            ganarColumna10--;
            ganarDiagonal20--;
            cambio = 1;

        } else if (fila == 3 && columna == 2 && f3c2 == 0 && jugador.equals("O")) {
            jLabelF3C2.setText(jugador);
            f3c2 = 1;
            ganarFila30--;
            ganarColumna20--;
            cambio = 1;

        } else if (fila == 3 && columna == 3 && f3c3 == 0 && jugador.equals("O")) {
            jLabelF3C3.setText(jugador);
            f3c3 = 1;
            ganarFila30--;
            ganarColumna30--;
            ganarDiagonal10--;
            cambio = 1;
        }

        //Ganar X
        if (ganarFila1X == 0) {
            resultado = "Ganó " + nombreX;
            Resultado.setText(resultado);
            Inicio_Registro.addPuntosX();
            fin = 1;

        } else if (ganarFila2X == 0) {
            resultado = "Ganó " + nombreX;
            Resultado.setText(resultado);
            Inicio_Registro.addPuntosX();
            fin = 1;

        } else if (ganarFila3X == 0) {
            resultado = "Ganó " + nombreX;
            Resultado.setText(resultado);
            Inicio_Registro.addPuntosX();
            fin = 1;

        } else if (ganarColumna1X == 0) {
            resultado = "Ganó " + nombreX;
            Resultado.setText(resultado);
            Inicio_Registro.addPuntosX();
            fin = 1;

        } else if (ganarColumna2X == 0) {
            resultado = "Ganó " + nombreX;
            Resultado.setText(resultado);
            Inicio_Registro.addPuntosX();
            fin = 1;

        } else if (ganarColumna3X == 0) {
            resultado = "Ganó " + nombreX;
            Resultado.setText(resultado);
            Inicio_Registro.addPuntosX();
            fin = 1;

        } else if (ganarDiagonal1X == 0) {
            resultado = "Ganó " + nombreX;
            Resultado.setText(resultado);
            Inicio_Registro.addPuntosX();
            fin = 1;

        } else if (ganarDiagonal2X == 0) {
            resultado = "Ganó " + nombreX;
            Resultado.setText(resultado);
            Inicio_Registro.addPuntosX();
            fin = 1;

            //Ganar 0
        } else if (ganarFila10 == 0) {
            resultado = "Ganó " + nombre0;
            Resultado.setText(resultado);
            Inicio_Registro.addPuntos0();
            fin = 1;

        } else if (ganarFila20 == 0) {
            resultado = "Ganó " + nombre0;
            Resultado.setText(resultado);
            Inicio_Registro.addPuntos0();
            fin = 1;

        } else if (ganarFila30 == 0) {
            resultado = "Ganó " + nombre0;
            Resultado.setText(resultado);
            Inicio_Registro.addPuntos0();
            fin = 1;

        } else if (ganarColumna10 == 0) {
            resultado = "Ganó " + nombre0;
            Resultado.setText(resultado);
            Inicio_Registro.addPuntos0();
            fin = 1;

        } else if (ganarColumna20 == 0) {
            resultado = "Ganó " + nombre0;
            Resultado.setText(resultado);
            Inicio_Registro.addPuntos0();
            fin = 1;

        } else if (ganarColumna30 == 0) {
            resultado = "Ganó " + nombre0;
            Resultado.setText(resultado);
            Inicio_Registro.addPuntos0();
            fin = 1;

        } else if (ganarDiagonal10 == 0) {
            resultado = "Ganó " + nombre0;
            Resultado.setText(resultado);
            Inicio_Registro.addPuntos0();
            fin = 1;

        } else if (ganarDiagonal20 == 0) {
            resultado = "Ganó " + nombre0;
            Resultado.setText(resultado);
            Inicio_Registro.addPuntos0();
            fin = 1;

            //Empate
        } else if (f1c1 == 1 && f1c2 == 1 && f1c3 == 1 && f2c1 == 1 && f2c2 == 1 && f2c3 == 1 && f3c1 == 1 && f3c2 == 1 && f3c3 == 1 && resultado.equals(" ")) {
            resultado = "Empate";
            Resultado.setText(resultado);
            fin = 1;

        }

        //Cambio de Turno
        if (jugador.equals("X") && cambio == 1) {
            jugador = "O";
            turno.setText("Turno de " + nombre0);

        } else if (jugador.equals("O") && cambio == 1) {
            jugador = "X";
            turno.setText("Turno de " + nombreX);
        }

        //Fin de partida
        if (fin == 1) {
            Resultado.setVisible(true);
            btnLimpiar.setVisible(true);
            btnSalir.setVisible(true);
        }

        CoordenadaFila.setText("");
        CoordenadaColumna.setText("");

    }//GEN-LAST:event_jButtonAceptarMouseClicked

    private void labelNombreXComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_labelNombreXComponentAdded

    }//GEN-LAST:event_labelNombreXComponentAdded

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked

        jugador = "X";

        f1c1 = 0;
        f1c2 = 0;
        f1c3 = 0;
        f2c1 = 0;
        f2c2 = 0;
        f2c3 = 0;
        f3c1 = 0;
        f3c2 = 0;
        f3c3 = 0;

        jLabelF1C1.setText("");
        jLabelF1C2.setText("");
        jLabelF1C3.setText("");
        jLabelF2C1.setText("");
        jLabelF2C2.setText("");
        jLabelF2C3.setText("");
        jLabelF3C1.setText("");
        jLabelF3C2.setText("");
        jLabelF3C3.setText("");

        ganarFila1X = 3;
        ganarFila2X = 3;
        ganarFila3X = 3;

        ganarFila10 = 3;
        ganarFila20 = 3;
        ganarFila30 = 3;

        ganarColumna1X = 3;
        ganarColumna2X = 3;
        ganarColumna3X = 3;

        ganarColumna10 = 3;
        ganarColumna20 = 3;
        ganarColumna30 = 3;

        ganarDiagonal1X = 3;
        ganarDiagonal2X = 3;
        ganarDiagonal10 = 3;
        ganarDiagonal20 = 3;

        CoordenadaFila.setText("");
        CoordenadaColumna.setText("");

        Resultado.setText("");

        btnLimpiar.setVisible(false);
        btnSalir.setVisible(false);
        Resultado.setVisible(false);

        fin = 0;
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        this.dispose();
        new Menu().setVisible(true);
    }//GEN-LAST:event_btnSalirMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CoordenadaColumna;
    private javax.swing.JTextField CoordenadaFila;
    private javax.swing.JLabel Ingrese;
    private javax.swing.JLabel Resultado;
    private javax.swing.JLabel X0;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JLabel jLabel0;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelColumna;
    private javax.swing.JLabel jLabelF1C1;
    private javax.swing.JLabel jLabelF1C2;
    private javax.swing.JLabel jLabelF1C3;
    private javax.swing.JLabel jLabelF2C1;
    private javax.swing.JLabel jLabelF2C2;
    private javax.swing.JLabel jLabelF2C3;
    private javax.swing.JLabel jLabelF3C1;
    private javax.swing.JLabel jLabelF3C2;
    private javax.swing.JLabel jLabelF3C3;
    private javax.swing.JLabel jLabelFila;
    private javax.swing.JLabel jLabelX;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanelF1C1;
    private javax.swing.JPanel jPanelF1C2;
    private javax.swing.JPanel jPanelF1C3;
    private javax.swing.JPanel jPanelF2C1;
    private javax.swing.JPanel jPanelF2C2;
    private javax.swing.JPanel jPanelF2C3;
    private javax.swing.JPanel jPanelF3C1;
    private javax.swing.JPanel jPanelF3C2;
    private javax.swing.JPanel jPanelF3C3;
    private javax.swing.JPanel jPanelRablero;
    private javax.swing.JLabel labelNombre0;
    private javax.swing.JLabel labelNombreX;
    private javax.swing.JLabel turno;
    // End of variables declaration//GEN-END:variables
}
